---
title: "Untitled"
author: "180212_my"
date: "2018년 6월 19일"
output: html_document
---
```{r}
df <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\data\\train.csv")
head(df)
names(df)
```

```{r}
test <- read.csv("C:\\Users\\202-22\\Documents\\R\\R2_Project\\R_Studio_exercise\\data\\test.csv")
head(test)
names(test)
```

```{r}
install.packages("corrplot")
library(corrplot)
```

```{r}
numericVars <- which(sapply(df, is.numeric))
numericVarNames <- names(numericVars)
numericVarNames
cat('There are', length(numericVars), 'numeric variables')
```

```{r}
all_numVar <- df[, numericVars]
cor_numVar <- cor(all_numVar, use="pairwise.complete.obs")
cor_numVar
```

```{r}
cor_sorted <- as.matrix(sort(cor_numVar[, 'SalePrice'], decreasing = TRUE))
cor_sorted
```

```{r}
mulcor = apply(cor_sorted, 1, function(x) abs(x)>0.5) # abs = absolute value
head(mulcor)
```

```{r}
CorHigh <- names(which(mulcor))
CorHigh
cor_numVar <- cor_numVar[CorHigh, CorHigh]
cor_numVar
```

```{r}
corrplot.mixed(cor_numVar, tl.col="black", tl.pos="lt")
```

```{r}
# practice with variable GarageCars
cor_numVar <- cor(all_numVar, use="pairwise.complete.obs")
cor_sorted <- as.matrix(sort(cor_numVar[, 'GarageCars'], decreasing = TRUE))
cor_sorted

```

```{r}
mulcor = apply(cor_sorted, 1, function(x) abs(x)>0.3) # abs = absolute value
head(mulcor)
```

```{r}
CorHigh <- names(which(mulcor))
cor_numVar <- cor_numVar[CorHigh, CorHigh]
cor_numVar
```

```{r}
corrplot.mixed(cor_numVar, tl.col="black", tl.pos="lt")
```

```{r}

```

