---
title: "Untitled"
author: "180212_my"
date: "2018년 4월 24일"
output: html_document
---

# KNN model
## 01. Load data
```{r}
data <- iris[, c("Sepal.Length", "Sepal.Width", "Species")]
str(data)
head(data)
```

## 02. Divide the dataset into 3 groups: train, validation, and test
```{r}
set.seed(1234)
# 1: train, 2: valid, 3: test
idx <- sample(x=c(1,2,3), size=nrow(data), replace=TRUE, prob=c(3,1,1))
idx
```

```{r}
train <- data[idx==1, ]
valid <- data[idx==2, ]
test <- data[idx==3, ]

dim(train) ; dim(valid) ; dim(test)
```

```{r}
install.packages("scales")
library(scales)
search()
```

```{r}
head(train)
```

```{r}
## train dataset
plot(Sepal.Length ~ Sepal.Width, data=train, col = train$Species, main = "Train, Valid, and Test dataset")

## valid dataset
points(Sepal.Length ~ Sepal.Width, data=valid, pch =17, cex=1.5, col="red")  # red triangle

## test dataset
points(Sepal.Length ~ Sepal.Width, data=test, pch=15, cex=1.5, col="blue")  # blue square

## legend 
legend("topright", c(levels(data$Species), "valid", "test"), 
       pch=c(1,1,1,17,15), 
       col=c("green", "red", "black", "red", "blue"),
       cex = 1.1)
```
## 04. Seperate x axis and y axis
```{r}
tr_x = train[, -3]
valid_x = valid[, -3]
test_x = test[, -3]

tr_y = train[, 3]
valid_y = valid[, 3]
test_y = test[, 3]

```

## Apply Knn
```{r}
install.packages('class')
library(class)
search()
```

```{r}
# if k = 1
dim(tr_x); dim(valid_x)

set.seed(1234)
knn_1 <- knn(train = tr_x,     # dataset to make a model
             test = valid_x,   # dataset to do knn classification
             cl = tr_y,        # based on this target variable (Species)
             k=1)              # number of k 
knn_1
```

## graph when k= 1
```{r}
plot(Sepal.Length ~ Sepal.Width,
     data= train,
     col=c("purple", "blue", "green")[train$Species],
     main="KNN gragh (k=1)")

points(Sepal.Length ~ Sepal.Width,
       data=valid,
       pch=17,
       cex=1.5,
       col=c("purple", "blue", "green")[knn_1])

legend("topright", 
       c( paste("train", levels(data$Species)), 
          paste("valid", levels(valid$Species))), 
       pch=c(rep(1,3), rep(17,3)), 
       col=c("purple", "blue", "green","purple", "blue", "green"), 
       cex = 1)
```

## Accuracy of the classification  
```{r}
accuracy_1 <- sum(knn_1 == valid_y)/length(valid_y) ; accuracy_1
```

## if k=21
```{r}
set.seed(1234)
knn_21 <- knn(train = tr_x,     # dataset to make a model
             test = valid_x,   # dataset to do knn classification
             cl = tr_y,        # based on this target variable (Species)
             k=21)              # number of k 
knn_21
```

```{r}
# test dataset
plot(formula = Sepal.Length ~ Sepal.Width,
     data = train, 
     col = c("purple", "blue", "green")[train$Species], 
     main = "KNN graph(k=21)")

# valid dataset
points(formula = Sepal.Length ~ Sepal.Width,
 data = valid,
 pch = 17,
 cex = 1.5,
 col = c("purple", "blue", "green")[knn_21])

# legend 그리기 (pch : 1- 원, pch : 17 : 세모)
legend("topright",
 c( paste("train", levels(data$Species)),
 paste("valid", levels(valid$Species))),
 pch=c(rep(1,3), rep(17,3)),  # repeat : (1,1,1), (17, 17, 17)
 col=c("purple", "blue", "green","purple", "blue", "green"),
 cex = 1)
```
## Accuracy of the classification when k = 21
```{r}
accuracy_21 <- sum(knn_21 == valid_y) / length(valid_y) ; accuracy_21
```

```{r}
accuracy_k <- NULL

for (kk in c(1:nrow(tr_x))) {
  set.seed(1234)
  knn_k <- knn(train = tr_x,
               test = valid_x,
               cl = tr_y,
               k=kk)
  accuracy_k <- c(accuracy_k, sum(knn_k == valid_y)/length(valid_y))
}

accuracy_k
```

```{r}
valid_k <- data.frame(k=c(1:nrow(tr_x)), accuracy= accuracy_k)
valid_k
```

```{r}
plot(accuracy ~ k, 
     data=valid_k,
     type="o",   # type="l" line, type="b" (both points and lines), type="o" lines over points
     pch=20,
     main="Validation - optimal k")

with(valid_k, text(accuracy~k, labels=rownames(valid_k),
                   pos=1, cex=0.7))
```

```{r}
# x %in% y : whether y is in x
min(valid_k[valid_k$accuracy %in% max(accuracy_k), "k"])
```

```{r}
set.seed(1234)
knn_13_test <- knn(train = tr_x,
                   test = test_x,
                   cl = tr_y,
                   k = 13)
knn_13_test

```

```{r}
# Confusion Matrix 틀 만들기
r = matrix(NA, nrow=3, ncol=3)
rownames(r) <- paste0("real_", levels(tr_y))
colnames(r) <- paste0("prev_", levels(tr_y))

# Confusion Matrix 값 입력하기
r[1, 1] <- sum(ifelse(test_y == "setosa" & knn_13_test == "setosa", 1, 0))
r[2, 1] <- sum(ifelse(test_y == "versicolor" & knn_13_test == "setosa", 1, 0))
r[3, 1] <- sum(ifelse(test_y == "virginica" & knn_13_test == "setosa", 1, 0))

r[1, 2] <- sum(ifelse(test_y == "setosa" & knn_13_test == "versicolor", 1, 0))
r[2, 2] <- sum(ifelse(test_y == "versicolor" & knn_13_test == "versicolor", 1, 0))
r[3, 2] <- sum(ifelse(test_y == "virginica" & knn_13_test == "versicolor", 1, 0))

r[1, 3] <- sum(ifelse(test_y == "setosa" & knn_13_test == "virginica", 1, 0))
r[2, 3] <- sum(ifelse(test_y == "versicolor" & knn_13_test == "virginica", 1, 0))
r[3, 3] <- sum(ifelse(test_y == "virginica" & knn_13_test == "virginica", 1, 0))

r
# 최종 정확도 계산
sum(knn_13_test==test_y)/sum(r)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

